# Generated by Django 4.2.16 on 2026-05-18 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipamentos', '0003_alter_equipamento_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chamados', '0009_alter_chamado_prioridade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('reservada', 'Reservada'), ('separada', 'Separada'), ('entregue', 'Entregue'), ('cancelada', 'Cancelada')], db_index=True, default='reservada', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('separated_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_estoque', to='chamados.chamado')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_estoque', to='equipamentos.equipamento')),
                ('item_solicitado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_estoque', to='chamados.chamadoitemsolicitado')),
                ('separado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_estoque_separadas', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_estoque_solicitadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reserva de estoque',
                'verbose_name_plural': 'Reservas de estoque',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='reservaestoque',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['reservada', 'separada'])), fields=('equipamento',), name='estoque_reserva_ativa_por_equipamento'),
        ),
    ]
