# Generated by Django 4.2.16 on 2026-05-11 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chamados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_patrimonio', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Patrimônio (Ativo)')),
                ('tipo', models.CharField(choices=[('adaptador', 'Adaptador'), ('cadeado_trava', 'Cadeado/Trava'), ('celular', 'Celular'), ('desktop_avancado', 'Desktop Avançado'), ('desktop_padrao', 'Desktop Padrão'), ('desktop_plus', 'Desktop Plus'), ('dockstation', 'Dockstation'), ('fone', 'Fone'), ('ipad_tablet', 'iPad/Tablet'), ('macbook', 'MacBook'), ('mochila', 'Mochila'), ('monitor', 'Monitor'), ('mouse', 'Mouse'), ('notebook_avancado', 'Notebook Avançado'), ('notebook_padrao', 'Notebook Padrão'), ('teclado', 'Teclado'), ('ultrabook', 'Ultrabook'), ('outro', 'Outro')], max_length=30, verbose_name='Tipo')),
                ('tipo_outro', models.CharField(blank=True, max_length=100, verbose_name='Tipo (outro)')),
                ('marca', models.CharField(blank=True, max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=100, verbose_name='Modelo')),
                ('service_tag', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Service Tag')),
                ('imei', models.CharField(blank=True, max_length=20, verbose_name='IMEI')),
                ('numero_serie', models.CharField(blank=True, max_length=100, verbose_name='Número de série')),
                ('monitor_patrimonio', models.CharField(blank=True, max_length=50, verbose_name='Monitor (patrimônio)')),
                ('status', models.CharField(choices=[('em_estoque', 'Em estoque'), ('em_uso', 'Em uso'), ('em_manutencao', 'Em manutenção'), ('descartado', 'Descartado'), ('aguardando', 'Aguardando aprovação')], db_index=True, default='em_estoque', max_length=20, verbose_name='Status')),
                ('condicao', models.CharField(choices=[('otimo', 'Ótimo'), ('bom', 'Bom'), ('regular', 'Regular'), ('ruim', 'Ruim'), ('inutil', 'Inútil')], default='bom', max_length=20, verbose_name='Condição')),
                ('data_atribuicao', models.DateTimeField(blank=True, null=True, verbose_name='Data de atribuição')),
                ('site', models.CharField(blank=True, max_length=100, verbose_name='Site')),
                ('setor', models.CharField(blank=True, max_length=100, verbose_name='Setor')),
                ('andar_sala', models.CharField(blank=True, max_length=50, verbose_name='Andar/Sala')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição/Observações')),
                ('data_aquisicao', models.DateField(blank=True, null=True, verbose_name='Data de aquisição')),
                ('valor_aquisicao', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor de aquisição (R$)')),
                ('garantia_ate', models.DateField(blank=True, null=True, verbose_name='Garantia até')),
                ('vida_util_estimada_meses', models.PositiveIntegerField(default=36, verbose_name='Vida útil estimada (meses)')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/', verbose_name='QR Code')),
                ('score_saude', models.FloatField(default=100.0, verbose_name='Score de saúde (IA)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipamentos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patrimonios', to=settings.AUTH_USER_MODEL, verbose_name='Responsável atual')),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'Equipamentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada em estoque'), ('saida', 'Saída para usuário'), ('devolucao', 'Devolução ao estoque'), ('manutencao', 'Envio para manutenção'), ('retorno_manutencao', 'Retorno da manutenção'), ('descarte', 'Descarte'), ('transferencia', 'Transferência'), ('troca', 'Troca de equipamento')], max_length=30, verbose_name='Tipo')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('chamado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes', to='chamados.chamado', verbose_name='Chamado vinculado')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='equipamentos.equipamento')),
                ('realizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Realizado por (técnico)')),
                ('usuario_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_saiu', to=settings.AUTH_USER_MODEL, verbose_name='Usuário anterior')),
                ('usuario_novo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_entrou', to=settings.AUTH_USER_MODEL, verbose_name='Novo usuário')),
            ],
            options={
                'verbose_name': 'Movimentação',
                'verbose_name_plural': 'Movimentações',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EntradaLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='lotes/', verbose_name='Arquivo Excel')),
                ('descricao', models.CharField(blank=True, max_length=200, verbose_name='Descrição do lote')),
                ('total_itens', models.PositiveIntegerField(default=0, verbose_name='Total de itens')),
                ('itens_importados', models.PositiveIntegerField(default=0, verbose_name='Itens importados')),
                ('itens_com_erro', models.PositiveIntegerField(default=0, verbose_name='Itens com erro')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('concluido', 'Concluído'), ('erro', 'Erro')], default='pendente', max_length=20, verbose_name='Status')),
                ('log_erros', models.TextField(blank=True, verbose_name='Log de erros')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrada em lote',
                'verbose_name_plural': 'Entradas em lote',
                'ordering': ['-created_at'],
            },
        ),
    ]
