# Generated by Django 6.0.4 on 2026-04-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entradalote',
            options={'ordering': ['-created_at'], 'verbose_name': 'Entrada em lote', 'verbose_name_plural': 'Entradas em lote'},
        ),
        migrations.AlterField(
            model_name='entradalote',
            name='descricao',
            field=models.CharField(blank=True, max_length=200, verbose_name='Descrição do lote'),
        ),
        migrations.AlterField(
            model_name='entradalote',
            name='itens_com_erro',
            field=models.PositiveIntegerField(default=0, verbose_name='Itens com erro'),
        ),
        migrations.AlterField(
            model_name='entradalote',
            name='itens_importados',
            field=models.PositiveIntegerField(default=0, verbose_name='Itens importados'),
        ),
        migrations.AlterField(
            model_name='entradalote',
            name='log_erros',
            field=models.TextField(blank=True, verbose_name='Log de erros'),
        ),
        migrations.AlterField(
            model_name='entradalote',
            name='total_itens',
            field=models.PositiveIntegerField(default=0, verbose_name='Total de itens'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='data_aquisicao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de aquisição'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='data_atribuicao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de atribuição'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=100, verbose_name='Número de série'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='score_saude',
            field=models.FloatField(default=100.0, verbose_name='Score de saúde (IA)'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='status',
            field=models.CharField(choices=[('em_estoque', 'Em estoque'), ('em_uso', 'Em uso'), ('em_manutencao', 'Em manutenção'), ('descartado', 'Descartado'), ('aguardando', 'Aguardando aprovação')], db_index=True, default='em_estoque', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='tipo',
            field=models.CharField(choices=[('adaptador', 'Adaptador'), ('cadeado_trava', 'Cadeado/Trava'), ('celular', 'Celular'), ('desktop_avancado', 'Desktop Avançado'), ('desktop_padrao', 'Desktop Padrão'), ('desktop_plus', 'Desktop Plus'), ('dockstation', 'Dockstation'), ('fone', 'Fone'), ('ipad_tablet', 'iPad/Tablet'), ('macbook', 'MacBook'), ('mochila', 'Mochila'), ('monitor', 'Monitor'), ('mouse', 'Mouse'), ('notebook_avancado', 'Notebook Avançado'), ('notebook_padrao', 'Notebook Padrão'), ('teclado', 'Teclado'), ('ultrabook', 'Ultrabook'), ('outro', 'Outro')], max_length=30, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='valor_aquisicao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor de aquisição (R$)'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='vida_util_estimada_meses',
            field=models.PositiveIntegerField(default=36, verbose_name='Vida útil estimada (meses)'),
        ),
        migrations.AlterField(
            model_name='movimentacaoequipamento',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada em estoque'), ('saida', 'Saída para usuário'), ('devolucao', 'Devolução ao estoque'), ('manutencao', 'Envio para manutenção'), ('retorno_manutencao', 'Retorno da manutenção'), ('descarte', 'Descarte'), ('transferencia', 'Transferência'), ('troca', 'Troca de equipamento')], max_length=30, verbose_name='Tipo'),
        ),
    ]
