# Generated by Django 4.2.16 on 2026-05-11 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgenteMonitoramento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome do agente')),
                ('token', models.CharField(db_index=True, editable=False, max_length=64, unique=True, verbose_name='Token')),
                ('host_name', models.CharField(blank=True, max_length=120, verbose_name='Host principal')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='Último heartbeat')),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Último IP')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Agente de monitoramento',
                'verbose_name_plural': 'Agentes de monitoramento',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TelemetriaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('heartbeat', 'Heartbeat'), ('conectado', 'Conectado'), ('desconectado', 'Desconectado'), ('bateria_baixa', 'Bateria baixa'), ('erro_driver', 'Erro de driver'), ('health_warning', 'Alerta de saude')], max_length=30, verbose_name='Tipo')),
                ('severidade', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=20, verbose_name='Severidade')),
                ('mensagem', models.TextField(blank=True, verbose_name='Mensagem')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Payload')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Evento de telemetria',
                'verbose_name_plural': 'Eventos de telemetria',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='equipamento',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Último heartbeat'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='last_telemetria_payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='Último payload de telemetria'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='monitoramento_ativo',
            field=models.BooleanField(default=False, verbose_name='Monitoramento ativo'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='monitoramento_status',
            field=models.CharField(choices=[('desconhecido', 'Desconhecido'), ('online', 'Online'), ('alerta', 'Alerta'), ('offline', 'Offline')], db_index=True, default='desconhecido', max_length=20, verbose_name='Status de monitoramento'),
        ),
        migrations.AddIndex(
            model_name='equipamento',
            index=models.Index(fields=['monitoramento_status', 'last_seen_at'], name='equipamento_monitor_c264fe_idx'),
        ),
        migrations.AddField(
            model_name='telemetriaevento',
            name='agente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='equipamentos.agentemonitoramento'),
        ),
        migrations.AddField(
            model_name='telemetriaevento',
            name='equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetria_eventos', to='equipamentos.equipamento'),
        ),
        migrations.AddField(
            model_name='agentemonitoramento',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agentes_monitoramento', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='last_telemetria_agente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipamentos_vistos', to='equipamentos.agentemonitoramento', verbose_name='Último agente'),
        ),
        migrations.AddIndex(
            model_name='telemetriaevento',
            index=models.Index(fields=['equipamento', '-created_at'], name='equipamento_equipam_d8e9dc_idx'),
        ),
        migrations.AddIndex(
            model_name='telemetriaevento',
            index=models.Index(fields=['agente', '-created_at'], name='equipamento_agente__5a6f44_idx'),
        ),
    ]
