# Generated by Django 4.2.16 on 2026-05-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0002_agentemonitoramento_telemetriaevento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='status',
            field=models.CharField(choices=[('em_estoque', 'Em estoque'), ('em_uso', 'Em uso'), ('em_manutencao', 'Em manutenção'), ('reservado', 'Reservado'), ('descartado', 'Descartado'), ('aguardando', 'Aguardando aprovação')], db_index=True, default='em_estoque', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='movimentacaoequipamento',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada em estoque'), ('reserva', 'Reserva de estoque'), ('liberacao_reserva', 'Liberação de reserva'), ('saida', 'Saída para usuário'), ('devolucao', 'Devolução ao estoque'), ('manutencao', 'Envio para manutenção'), ('retorno_manutencao', 'Retorno da manutenção'), ('descarte', 'Descarte'), ('transferencia', 'Transferência'), ('troca', 'Troca de equipamento')], max_length=30, verbose_name='Tipo'),
        ),
    ]
