# Generated by Django 5.2.16 on 2026-08-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0003_alter_equipamento_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='especificacoes',
            field=models.JSONField(blank=True, default=dict, help_text='Dados específicos do equipamento (CPU, RAM, GPU, etc.)', verbose_name='Especificações'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='tipo',
            field=models.CharField(choices=[('adaptador', 'Adaptador'), ('accesspoint', 'Access Point'), ('cadeado_trava', 'Cadeado/Trava'), ('celular', 'Celular'), ('desktop_avancado', 'Desktop Avançado'), ('desktop_padrao', 'Desktop Padrão'), ('desktop_plus', 'Desktop Plus'), ('dockstation', 'Dockstation'), ('fone', 'Fone'), ('ipad_tablet', 'iPad/Tablet'), ('macbook', 'MacBook'), ('mochila', 'Mochila'), ('monitor', 'Monitor'), ('mouse', 'Mouse'), ('notebook_avancado', 'Notebook Avançado'), ('notebook_padrao', 'Notebook Padrão'), ('qsfp', 'QSFP'), ('sfp', 'SFP'), ('switch', 'Switch'), ('teclado', 'Teclado'), ('ultrabook', 'Ultrabook'), ('outro', 'Outro')], max_length=30, verbose_name='Tipo'),
        ),
    ]
