# Generated by Django 5.2.16 on 2026-08-17 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0005_alter_equipamento_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='fornecedor',
            field=models.CharField(blank=True, max_length=150, verbose_name='Fornecedor'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='usuario_windows_esperado',
            field=models.CharField(blank=True, max_length=150, verbose_name='Usuário Windows esperado'),
        ),
        migrations.AddField(
            model_name='movimentacaoequipamento',
            name='custo_manutencao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Custo da manutenção (R$)'),
        ),
        migrations.AddField(
            model_name='movimentacaoequipamento',
            name='fornecedor_manutencao',
            field=models.CharField(blank=True, max_length=150, verbose_name='Fornecedor da manutenção'),
        ),
        migrations.CreateModel(
            name='AlertaCicloVida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('garantia', 'Garantia'), ('substituicao', 'Substituição'), ('manutencao_recorrente', 'Manutenção recorrente'), ('custo_manutencao', 'Custo de manutenção'), ('condicao', 'Condição')], max_length=40, verbose_name='Tipo')),
                ('severidade', models.CharField(choices=[('warning', 'Atenção'), ('critical', 'Crítico')], max_length=20, verbose_name='Severidade')),
                ('titulo', models.CharField(max_length=160, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
                ('detectado_em', models.DateTimeField(auto_now_add=True, verbose_name='Detectado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('resolvido_em', models.DateTimeField(blank=True, null=True, verbose_name='Resolvido em')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_ciclo_vida', to='equipamentos.equipamento')),
            ],
            options={
                'verbose_name': 'Alerta de ciclo de vida',
                'verbose_name_plural': 'Alertas de ciclo de vida',
                'ordering': ['-ativo', '-atualizado_em'],
                'indexes': [models.Index(fields=['ativo', 'severidade'], name='equipamento_ativo_e7512d_idx')],
                'constraints': [models.UniqueConstraint(fields=('equipamento', 'tipo'), name='unique_lifecycle_alert_per_asset')],
            },
        ),
        migrations.CreateModel(
            name='DivergenciaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(choices=[('memoria', 'Memória'), ('armazenamento', 'Armazenamento'), ('serial', 'Serial'), ('usuario', 'Usuário atual')], max_length=30, verbose_name='Campo')),
                ('valor_cadastrado', models.CharField(max_length=255, verbose_name='Valor cadastrado')),
                ('valor_detectado', models.CharField(max_length=255, verbose_name='Valor detectado')),
                ('ativa', models.BooleanField(db_index=True, default=True, verbose_name='Ativa')),
                ('detectada_em', models.DateTimeField(auto_now_add=True, verbose_name='Detectada em')),
                ('ultima_verificacao_em', models.DateTimeField(auto_now=True, verbose_name='Última verificação')),
                ('resolvida_em', models.DateTimeField(blank=True, null=True, verbose_name='Resolvida em')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divergencias_inventario', to='equipamentos.equipamento')),
            ],
            options={
                'verbose_name': 'Divergência de inventário',
                'verbose_name_plural': 'Divergências de inventário',
                'ordering': ['-ativa', '-ultima_verificacao_em'],
                'indexes': [models.Index(fields=['ativa', 'campo'], name='equipamento_ativa_2f2079_idx')],
                'constraints': [models.UniqueConstraint(fields=('equipamento', 'campo'), name='unique_inventory_divergence_per_field')],
            },
        ),
    ]
