# Generated by Django 4.2.16 on 2026-05-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='tipo_equipamento_solicitado',
            field=models.CharField(blank=True, choices=[('adaptador', 'Adaptador'), ('cadeado_trava', 'Cadeado/Trava'), ('celular', 'Celular'), ('desktop_avancado', 'Desktop Avançado'), ('desktop_padrao', 'Desktop Padrão'), ('desktop_plus', 'Desktop Plus'), ('dockstation', 'Dockstation'), ('fone', 'Fone'), ('ipad_tablet', 'iPad/Tablet'), ('macbook', 'MacBook'), ('mochila', 'Mochila'), ('monitor', 'Monitor'), ('mouse', 'Mouse'), ('notebook_avancado', 'Notebook Avançado'), ('notebook_padrao', 'Notebook Padrão'), ('teclado', 'Teclado'), ('ultrabook', 'Ultrabook'), ('outro', 'Outro')], db_index=True, default='', max_length=30),
        ),
    ]
