# Generated by Django 4.2.16 on 2026-05-11 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0003_chamado_tipo_equipamento_solicitado'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='servico_realizado',
            field=models.CharField(blank=True, choices=[('entrega', 'Entrega de equipamento'), ('recolhimento', 'Recolhimento de equipamento'), ('troca', 'Troca de equipamento'), ('manutencao', 'Manutenção'), ('instalacao', 'Instalação / configuração'), ('orientacao', 'Orientação'), ('outro', 'Outro')], db_index=True, default='', max_length=30),
        ),
        migrations.CreateModel(
            name='ChamadoItemSolicitado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_equipamento', models.CharField(choices=[('adaptador', 'Adaptador'), ('cadeado_trava', 'Cadeado/Trava'), ('celular', 'Celular'), ('desktop_avancado', 'Desktop Avançado'), ('desktop_padrao', 'Desktop Padrão'), ('desktop_plus', 'Desktop Plus'), ('dockstation', 'Dockstation'), ('fone', 'Fone'), ('ipad_tablet', 'iPad/Tablet'), ('macbook', 'MacBook'), ('mochila', 'Mochila'), ('monitor', 'Monitor'), ('mouse', 'Mouse'), ('notebook_avancado', 'Notebook Avançado'), ('notebook_padrao', 'Notebook Padrão'), ('teclado', 'Teclado'), ('ultrabook', 'Ultrabook'), ('outro', 'Outro')], max_length=30)),
                ('tipo_outro', models.CharField(blank=True, max_length=100)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('observacao', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_solicitados', to='chamados.chamado')),
            ],
            options={
                'verbose_name': 'Item solicitado',
                'verbose_name_plural': 'Itens solicitados',
                'ordering': ['id'],
            },
        ),
    ]
