# Generated by Django 4.2.16 on 2026-05-12 00:00

from django.db import migrations, models


def forwards(apps, schema_editor):
    Chamado = apps.get_model('chamados', 'Chamado')
    for status_antigo, status_novo in {
        'aberto': 'fila',
        'em_analise': 'fila',
        'aguardando_usuario': 'aguardando_atendimento',
        'resolvido': 'encerrado',
        'fechado': 'encerrado',
    }.items():
        Chamado.objects.filter(status=status_antigo).update(status=status_novo)


def backwards(apps, schema_editor):
    Chamado = apps.get_model('chamados', 'Chamado')
    for status_novo, status_antigo in {
        'fila': 'aberto',
        'aguardando_atendimento': 'aguardando_usuario',
        'encerrado': 'fechado',
    }.items():
        Chamado.objects.filter(status=status_novo).update(status=status_antigo)


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0004_chamado_servico_realizado_chamadoitemsolicitado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='status',
            field=models.CharField(
                choices=[
                    ('fila', 'Fila'),
                    ('em_atendimento', 'Em atendimento'),
                    ('aguardando_atendimento', 'Aguardando atendimento'),
                    ('encerrado', 'Encerrado'),
                ],
                default='fila',
                max_length=30,
            ),
        ),
        migrations.RunPython(forwards, backwards),
    ]
