# Generated by Django 4.2.16 on 2026-05-12 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0002_agentemonitoramento_telemetriaevento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chamados', '0005_chamado_status_fluxo'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamadoitemsolicitado',
            name='entregue_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chamadoitemsolicitado',
            name='entregue_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_chamado_entregues', to=settings.AUTH_USER_MODEL, verbose_name='Entregue por'),
        ),
        migrations.AddField(
            model_name='chamadoitemsolicitado',
            name='equipamento_entregue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_chamado_entregues', to='equipamentos.equipamento', verbose_name='Equipamento entregue'),
        ),
    ]
