# Generated by Django 4.2.16 on 2026-05-12 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chamados', '0006_chamadoitemsolicitado_entregue_em_and_more'),
    ]

    def forwards(apps, schema_editor):
        Chamado = apps.get_model('chamados', 'Chamado')
        for chamado in Chamado.objects.filter(destinatario__isnull=True).exclude(solicitante__isnull=True).only('id', 'solicitante_id'):
            chamado.destinatario_id = chamado.solicitante_id
            chamado.save(update_fields=['destinatario'])

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='destinatario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados_destinatario', to=settings.AUTH_USER_MODEL, verbose_name='Colaborador'),
        ),
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
