# Generated by Django 4.2.16 on 2026-05-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0008_chamado_fluxo_etapa_aprovacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='prioridade',
            field=models.CharField(choices=[('baixa', 'Baixa'), ('media', 'MÃ©dia'), ('alta', 'Alta'), ('critica', 'CrÃ\xadtica')], default='media', max_length=20),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='servico_realizado',
            field=models.CharField(blank=True, choices=[('entrega', 'Entrega de equipamento'), ('recolhimento', 'Recolhimento de equipamento'), ('troca', 'Troca de equipamento'), ('manutencao', 'ManutenÃ§Ã£o'), ('instalacao', 'InstalaÃ§Ã£o / configuraÃ§Ã£o'), ('orientacao', 'OrientaÃ§Ã£o'), ('outro', 'Outro')], db_index=True, default='', max_length=30),
        ),
    ]
