# Generated by Django 4.2.16 on 2026-05-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0009_alter_chamado_prioridade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='sla_alertado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chamado',
            name='sla_escalado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chamado',
            name='sla_nivel',
            field=models.CharField(choices=[('normal', 'Dentro do prazo'), ('alerta', 'Em alerta'), ('escalado', 'Escalonado')], db_index=True, default='normal', max_length=20),
        ),
    ]
