# Generated by Codex on 2026-08-04

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chamados', '0010_chamado_sla_alertado_em_chamado_sla_escalado_em_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermoAceiteDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Token publico')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('assinado', 'Assinado')], db_index=True, default='pendente', max_length=20, verbose_name='Status')),
                ('nome_assinante', models.CharField(blank=True, max_length=150, verbose_name='Nome do assinante')),
                ('matricula_assinante', models.CharField(blank=True, max_length=20, verbose_name='Matricula do assinante')),
                ('assinatura_data_url', models.TextField(blank=True, verbose_name='Assinatura capturada')),
                ('documento_hash', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Hash SHA-256 do termo')),
                ('ip_assinatura', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP da assinatura')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='User agent')),
                ('assinado_em', models.DateTimeField(blank=True, null=True, verbose_name='Assinado em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('assinado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='termos_assinados', to=settings.AUTH_USER_MODEL, verbose_name='Assinado por')),
                ('chamado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aceite_digital', to='chamados.chamado', verbose_name='Chamado')),
            ],
            options={
                'verbose_name': 'Aceite digital de termo',
                'verbose_name_plural': 'Aceites digitais de termos',
                'ordering': ['-created_at'],
            },
        ),
    ]
