# Generated by Django 5.2.16 on 2026-08-04 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import chamados.models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0011_termoaceitedigital'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='termoaceitedigital',
            name='email_destino',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail de destino'),
        ),
        migrations.AddField(
            model_name='termoaceitedigital',
            name='email_enviado',
            field=models.BooleanField(default=False, verbose_name='E-mail enviado'),
        ),
        migrations.AddField(
            model_name='termoaceitedigital',
            name='enviado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Enviado em'),
        ),
        migrations.AddField(
            model_name='termoaceitedigital',
            name='enviado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='termos_enviados', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por'),
        ),
        migrations.AddField(
            model_name='termoaceitedigital',
            name='envio_total',
            field=models.PositiveIntegerField(default=0, verbose_name='Total de envios'),
        ),
        migrations.AddField(
            model_name='termoaceitedigital',
            name='expires_at',
            field=models.DateTimeField(db_index=True, default=chamados.models.termo_aceite_expires_at, verbose_name='Expira em'),
        ),
    ]
