# Generated by Django 5.2.16 on 2026-08-04 16:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def backfill_evento_inicial_fluxo(apps, schema_editor):
    Chamado = apps.get_model('chamados', 'Chamado')
    ChamadoFluxoEvento = apps.get_model('chamados', 'ChamadoFluxoEvento')
    eventos = []
    for chamado in Chamado.objects.all().only('id', 'status', 'fluxo_etapa', 'created_at').iterator():
        eventos.append(
            ChamadoFluxoEvento(
                chamado_id=chamado.id,
                etapa_anterior='',
                etapa_nova=chamado.fluxo_etapa or 'solicitado',
                status_anterior='',
                status_novo=chamado.status or 'fila',
                observacao='Backfill historico inicial.',
                criado_em=chamado.created_at,
            )
        )
    if eventos:
        ChamadoFluxoEvento.objects.bulk_create(eventos, batch_size=1000)


def remover_backfill_evento_inicial_fluxo(apps, schema_editor):
    ChamadoFluxoEvento = apps.get_model('chamados', 'ChamadoFluxoEvento')
    ChamadoFluxoEvento.objects.filter(observacao='Backfill historico inicial.').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0012_termoaceitedigital_email_destino_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChamadoFluxoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa_anterior', models.CharField(blank=True, choices=[('solicitado', 'Solicitado'), ('triagem', 'Em triagem'), ('aguardando_estoque', 'Aguardando estoque'), ('aguardando_aprovacao', 'Aguardando aprovação'), ('aprovado_para_retirada', 'Aprovado para retirada'), ('em_separacao', 'Em separação'), ('pronto_para_entrega', 'Pronto para entrega'), ('encerrado', 'Encerrado')], default='', max_length=40, verbose_name='Etapa anterior')),
                ('etapa_nova', models.CharField(choices=[('solicitado', 'Solicitado'), ('triagem', 'Em triagem'), ('aguardando_estoque', 'Aguardando estoque'), ('aguardando_aprovacao', 'Aguardando aprovação'), ('aprovado_para_retirada', 'Aprovado para retirada'), ('em_separacao', 'Em separação'), ('pronto_para_entrega', 'Pronto para entrega'), ('encerrado', 'Encerrado')], max_length=40, verbose_name='Nova etapa')),
                ('status_anterior', models.CharField(blank=True, choices=[('fila', 'Fila'), ('em_atendimento', 'Em atendimento'), ('aguardando_atendimento', 'Aguardando atendimento'), ('encerrado', 'Encerrado')], default='', max_length=30, verbose_name='Status anterior')),
                ('status_novo', models.CharField(choices=[('fila', 'Fila'), ('em_atendimento', 'Em atendimento'), ('aguardando_atendimento', 'Aguardando atendimento'), ('encerrado', 'Encerrado')], max_length=30, verbose_name='Novo status')),
                ('observacao', models.CharField(blank=True, max_length=160, verbose_name='Observacao')),
                ('criado_em', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Criado em')),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fluxo_eventos', to='chamados.chamado', verbose_name='Chamado')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_fluxo_chamados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario da acao')),
            ],
            options={
                'verbose_name': 'Evento de fluxo do chamado',
                'verbose_name_plural': 'Eventos de fluxo dos chamados',
                'ordering': ['criado_em', 'id'],
                'indexes': [models.Index(fields=['chamado', 'criado_em'], name='chamados_ch_chamado_f4d3b0_idx'), models.Index(fields=['etapa_nova', 'criado_em'], name='chamados_ch_etapa_n_3f243e_idx')],
            },
        ),
        migrations.RunPython(backfill_evento_inicial_fluxo, remover_backfill_evento_inicial_fluxo),
    ]
