# Generated by Django 5.2.16 on 2026-08-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0013_chamadofluxoevento'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamadofluxoevento',
            name='sla_alertado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='SLA da etapa alertado em'),
        ),
        migrations.AddField(
            model_name='chamadofluxoevento',
            name='sla_escalado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='SLA da etapa escalado em'),
        ),
    ]
