# Generated by Django 5.2.16 on 2026-08-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0014_chamadofluxoevento_sla_alertado_em_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='tipo_equipamento_solicitado',
            field=models.CharField(blank=True, choices=[('adaptador', 'Adaptador'), ('accesspoint', 'Access Point'), ('cadeado_trava', 'Cadeado/Trava'), ('celular', 'Celular'), ('desktop_avancado', 'Desktop Avançado'), ('desktop_padrao', 'Desktop Padrão'), ('desktop_plus', 'Desktop Plus'), ('dockstation', 'Dockstation'), ('fibra_optica', 'Fibra Óptica'), ('fone', 'Fone'), ('ipad_tablet', 'iPad/Tablet'), ('macbook', 'MacBook'), ('mochila', 'Mochila'), ('monitor', 'Monitor'), ('mouse', 'Mouse'), ('notebook_avancado', 'Notebook Avançado'), ('notebook_padrao', 'Notebook Padrão'), ('qsfp', 'QSFP'), ('sfp', 'SFP'), ('switch', 'Switch'), ('teclado', 'Teclado'), ('ultrabook', 'Ultrabook'), ('outro', 'Outro')], db_index=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='chamadoitemsolicitado',
            name='tipo_equipamento',
            field=models.CharField(choices=[('adaptador', 'Adaptador'), ('accesspoint', 'Access Point'), ('cadeado_trava', 'Cadeado/Trava'), ('celular', 'Celular'), ('desktop_avancado', 'Desktop Avançado'), ('desktop_padrao', 'Desktop Padrão'), ('desktop_plus', 'Desktop Plus'), ('dockstation', 'Dockstation'), ('fibra_optica', 'Fibra Óptica'), ('fone', 'Fone'), ('ipad_tablet', 'iPad/Tablet'), ('macbook', 'MacBook'), ('mochila', 'Mochila'), ('monitor', 'Monitor'), ('mouse', 'Mouse'), ('notebook_avancado', 'Notebook Avançado'), ('notebook_padrao', 'Notebook Padrão'), ('qsfp', 'QSFP'), ('sfp', 'SFP'), ('switch', 'Switch'), ('teclado', 'Teclado'), ('ultrabook', 'Ultrabook'), ('outro', 'Outro')], max_length=30),
        ),
    ]
