# Generated by Django 5.2.16 on 2026-08-12 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_limit_backup_retention_to_30_days'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemHealthComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_key', models.CharField(max_length=50, unique=True, verbose_name='Componente')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('status', models.CharField(choices=[('healthy', 'Saudavel'), ('warning', 'Atencao'), ('critical', 'Critico'), ('unknown', 'Sem dados')], db_index=True, default='unknown', max_length=20, verbose_name='Status')),
                ('summary', models.CharField(blank=True, max_length=255, verbose_name='Resumo')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Detalhes')),
                ('source', models.CharField(default='scheduled', max_length=20, verbose_name='Origem')),
                ('checked_at', models.DateTimeField(verbose_name='Verificado em')),
                ('status_changed_at', models.DateTimeField(verbose_name='Status alterado em')),
                ('last_notified_status', models.CharField(blank=True, max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Componente de saude',
                'verbose_name_plural': 'Componentes de saude',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SystemHealthEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_key', models.CharField(db_index=True, max_length=50, verbose_name='Componente')),
                ('component_name', models.CharField(max_length=100, verbose_name='Nome')),
                ('previous_status', models.CharField(blank=True, max_length=20, verbose_name='Status anterior')),
                ('status', models.CharField(choices=[('healthy', 'Saudavel'), ('warning', 'Atencao'), ('critical', 'Critico'), ('unknown', 'Sem dados')], db_index=True, max_length=20, verbose_name='Status')),
                ('summary', models.CharField(max_length=255, verbose_name='Resumo')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Detalhes')),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ocorrido em')),
            ],
            options={
                'verbose_name': 'Evento de saude',
                'verbose_name_plural': 'Eventos de saude',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='RestoreValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tested_at', models.DateTimeField(verbose_name='Testado em')),
                ('result', models.CharField(choices=[('success', 'Aprovado'), ('failed', 'Falhou')], max_length=20, verbose_name='Resultado')),
                ('backup_manifest', models.CharField(max_length=255, verbose_name='Ponto utilizado')),
                ('notes', models.TextField(blank=True, verbose_name='Observacoes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restore_validations_recorded', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Validacao de restauracao',
                'verbose_name_plural': 'Validacoes de restauracao',
                'ordering': ['-tested_at', '-created_at'],
            },
        ),
    ]
