from django.urls import path

from .views import (
    assinar_termo_chamado,
    compliance_termos_chamados,
    compliance_termos_csv,
    compliance_termos_pdf,
    criar_chamado,
    detalhe_chamado,
    editar_chamado,
    entregar_equipamento_chamado,
    enviar_assinatura_termo,
    excluir_chamado,
    fluxo_chamado_action,
    lista_chamados,
    painel_tecnico,
    painel_termos_chamados,
    produtividade_operacional,
    renovar_assinatura_termo,
    termo_chamado,
    termo_chamado_pdf,
)

urlpatterns = [
    path('', lista_chamados, name='chamados'),
    path('painel/', painel_tecnico, name='painel_tecnico'),
    path('produtividade/', produtividade_operacional, name='produtividade_operacional'),
    path('novo/', criar_chamado, name='criar_chamado'),
    path('termos/', painel_termos_chamados, name='painel_termos_chamados'),
    path('termos/compliance/', compliance_termos_chamados, name='compliance_termos_chamados'),
    path('termos/compliance.csv', compliance_termos_csv, name='compliance_termos_csv'),
    path('termos/compliance.pdf', compliance_termos_pdf, name='compliance_termos_pdf'),
    path('termos/assinatura/<uuid:token>/', assinar_termo_chamado, name='assinar_termo_chamado'),
    path('<int:pk>/', detalhe_chamado, name='detalhe_chamado'),
    path('<int:pk>/fluxo/', fluxo_chamado_action, name='fluxo_chamado_action'),
    path('<int:pk>/termo/', termo_chamado, name='termo_chamado'),
    path('<int:pk>/termo/pdf/', termo_chamado_pdf, name='termo_chamado_pdf'),
    path('<int:pk>/termo/enviar-assinatura/', enviar_assinatura_termo, name='enviar_assinatura_termo'),
    path('<int:pk>/termo/renovar-assinatura/', renovar_assinatura_termo, name='renovar_assinatura_termo'),
    path('<int:pk>/editar/', editar_chamado, name='editar_chamado'),
    path('<int:pk>/excluir/', excluir_chamado, name='excluir_chamado'),
    path('<int:pk>/entregar/', entregar_equipamento_chamado, name='entregar_equipamento_chamado'),
]
