# Generated by Django 6.0.4 on 2026-04-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['first_name', 'last_name', 'matricula'], 'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AlterField(
            model_name='usuario',
            name='matricula',
            field=models.CharField(max_length=20, unique=True, verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nivel_acesso',
            field=models.CharField(choices=[('viewer', 'Solicitante'), ('tecnico', 'Técnico'), ('analista', 'Analista'), ('admin', 'Administrador')], default='viewer', max_length=20, verbose_name='Nível de acesso'),
        ),
    ]
