# Generated by Django 5.2.16 on 2026-08-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='two_factor_confirmed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='2FA confirmado em'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='two_factor_enabled',
            field=models.BooleanField(default=False, verbose_name='Autenticação em dois fatores ativa'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='two_factor_last_counter',
            field=models.BigIntegerField(blank=True, editable=False, null=True, verbose_name='Contador TOTP utilizado'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='two_factor_recovery_hashes',
            field=models.JSONField(blank=True, default=list, editable=False, verbose_name='Códigos de recuperação 2FA'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='two_factor_secret_encrypted',
            field=models.TextField(blank=True, editable=False, verbose_name='Segredo 2FA criptografado'),
        ),
    ]
