# Generated by Django 6.0.4 on 2026-04-30 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_usuario_options_alter_usuario_matricula_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='aprovado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Aprovado em'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='aprovado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprovacoes_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Aprovado por'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='exigir_troca_senha',
            field=models.BooleanField(default=False, verbose_name='Exigir troca de senha'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='motivo_recusa',
            field=models.TextField(blank=True, verbose_name='Motivo da recusa'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='solicitacao_pendente',
            field=models.BooleanField(default=False, verbose_name='Solicitação pendente'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='matricula',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Matrícula'),
        ),
    ]
